INSERT INTO `category`(`category_id`, `category_title`, `category_createBy`) VALUES ('C100', 'Organic Food', 'AD03');
INSERT INTO `category`(`category_id`, `category_title`, `category_createBy`) VALUES ('C101', 'Healthful Food', 'AD02');
INSERT INTO `category`(`category_id`, `category_title`, `category_createBy`) VALUES ('C102', 'Lite Food', 'AD01');
INSERT INTO `category`(`category_id`, `category_title`, `category_createBy`) VALUES ('C103', 'Super Food', 'AD03');
INSERT INTO `category`(`category_id`, `category_title`, `category_createBy`) VALUES ('C200', 'Chemical Food', 'AD02');
INSERT INTO `category`(`category_id`, `category_title`, `category_createBy`) VALUES ('C300', 'Fruits', 'AD03');
INSERT INTO `category`(`category_id`, `category_title`, `category_createBy`) VALUES ('C301', 'Skinny Food', 'AD01');
INSERT INTO `category`(`category_id`, `category_title`, `category_createBy`) VALUES ('C302', 'Low-Calorie', 'AD03');
INSERT INTO `category`(`category_id`, `category_title`, `category_createBy`) VALUES ('C303', 'Lite Food', 'AD02');
INSERT INTO `category`(`category_id`, `category_title`, `category_createBy`) VALUES ('C304', 'Non-Fat', 'AD01');
INSERT INTO `category`(`category_id`, `category_title`, `category_createBy`) VALUES ('C305', 'Peanut', 'AD03');
